/* 
 * AUTO-GENERATED FILE. DO NOT EDIT.
 * Generated by gen_enum.c 
 */
#include "lexer.h"
#include "parser.h"
#include "intercode.h"

// Auto-generated function for tokentype_t
const char* tokentype_tostr(tokentype_t type) {
  switch(type) {
    case LET: return "LET";
    case FN: return "FN";
    case IF: return "IF";
    case ELSE: return "ELSE";
    case WHILE: return "WHILE";
    case RETURN: return "RETURN";
    case EXTERN: return "EXTERN";
    case BREAK: return "BREAK";
    case CLASS: return "CLASS";
    case INCLUDE: return "INCLUDE";
    case INT: return "INT";
    case STRING: return "STRING";
    case VOID: return "VOID";
    case TYPE_KEYWORD: return "TYPE_KEYWORD";
    case WHITESPACE: return "WHITESPACE";
    case COMMA: return "COMMA";
    case SEMICOLON: return "SEMICOLON";
    case COLON: return "COLON";
    case QUOTE: return "QUOTE";
    case DOUBLE_QUOTE: return "DOUBLE_QUOTE";
    case OPENPAREN: return "OPENPAREN";
    case CLOSEPAREN: return "CLOSEPAREN";
    case OPEN_SQUAREBRACKET: return "OPEN_SQUAREBRACKET";
    case CLOSE_SQUAREBRACKET: return "CLOSE_SQUAREBRACKET";
    case OPENBRACE: return "OPENBRACE";
    case CLOSEBRACE: return "CLOSEBRACE";
    case ADD: return "ADD";
    case SUB: return "SUB";
    case MUL: return "MUL";
    case DIV: return "DIV";
    case MOD: return "MOD";
    case BITAND: return "BITAND";
    case BITOR: return "BITOR";
    case XOR: return "XOR";
    case DOT: return "DOT";
    case EQUAL: return "EQUAL";
    case GREATER: return "GREATER";
    case LESS: return "LESS";
    case GREATER_EQUAL: return "GREATER_EQUAL";
    case LESS_EQUAL: return "LESS_EQUAL";
    case NOT_EQUAL: return "NOT_EQUAL";
    case ASSIGN: return "ASSIGN";
    case AND: return "AND";
    case OR: return "OR";
    case NOT: return "NOT";
    case IDENTIFIER: return "IDENTIFIER";
    case CONSTANT_NUMBER: return "CONSTANT_NUMBER";
    case CONSTANT_STRING: return "CONSTANT_STRING";
    case CONSTANT_CHAR: return "CONSTANT_CHAR";
    case TOKEN_VALUE: return "TOKEN_VALUE";
    case TOKEN_ID: return "TOKEN_ID";
    case TOKEN_TYPEKW: return "TOKEN_TYPEKW";
    case TOKEN_EXPR: return "TOKEN_EXPR";
    case TOKEN_EXPR_COND: return "TOKEN_EXPR_COND";
    case TOKEN_STATEMENTS: return "TOKEN_STATEMENTS";
    case TOKEN_ARGLIST: return "TOKEN_ARGLIST";
    case TOKEN_CLASS_MEMBERDEF: return "TOKEN_CLASS_MEMBERDEF";
    default: return "UNKNOWN_tokentype_t";
  }
}

// Auto-generated function for astnode_type_t
const char* get_nodetype_str(astnode_type_t type) {
  switch(type) {
    case NODE_NONE: return "NODE_NONE";
    case NODE_LEAFHOLDER: return "NODE_LEAFHOLDER";
    case NODE_SINGLEEXPR: return "NODE_SINGLEEXPR";
    case NODE_CONSTANT: return "NODE_CONSTANT";
    case NODE_IDENTIFIER: return "NODE_IDENTIFIER";
    case NODE_IF: return "NODE_IF";
    case NODE_ELSEIF: return "NODE_ELSEIF";
    case NODE_ELSE: return "NODE_ELSE";
    case NODE_WHILE: return "NODE_WHILE";
    case NODE_RETURN: return "NODE_RETURN";
    case NODE_BREAK: return "NODE_BREAK";
    case NODE_FUNCTION: return "NODE_FUNCTION";
    case NODE_DEFINITION: return "NODE_DEFINITION";
    case NODE_EXTERN: return "NODE_EXTERN";
    case NODE_DECLARE_VAR: return "NODE_DECLARE_VAR";
    case NODE_DECLARE_FUNC: return "NODE_DECLARE_FUNC";
    case NODE_CLASS: return "NODE_CLASS";
    case NODE_INCLUDE: return "NODE_INCLUDE";
    case NODE_COMMALIST: return "NODE_COMMALIST";
    case NODE_ADD: return "NODE_ADD";
    case NODE_SUB: return "NODE_SUB";
    case NODE_MUL: return "NODE_MUL";
    case NODE_DIV: return "NODE_DIV";
    case NODE_MOD: return "NODE_MOD";
    case NODE_REFER: return "NODE_REFER";
    case NODE_DEFER: return "NODE_DEFER";
    case NODE_BITAND: return "NODE_BITAND";
    case NODE_BITOR: return "NODE_BITOR";
    case NODE_XOR: return "NODE_XOR";
    case NODE_PROPERTY: return "NODE_PROPERTY";
    case NODE_INDEX: return "NODE_INDEX";
    case NODE_EQUAL: return "NODE_EQUAL";
    case NODE_GREATER: return "NODE_GREATER";
    case NODE_LESS: return "NODE_LESS";
    case NODE_GREATER_EQUAL: return "NODE_GREATER_EQUAL";
    case NODE_LESS_EQUAL: return "NODE_LESS_EQUAL";
    case NODE_NOT_EQUAL: return "NODE_NOT_EQUAL";
    case NODE_ASSIGN: return "NODE_ASSIGN";
    case NODE_AND: return "NODE_AND";
    case NODE_OR: return "NODE_OR";
    case NODE_NOT: return "NODE_NOT";
    case NODE_FUNCCALL: return "NODE_FUNCCALL";
    case NODE_POINTEROF: return "NODE_POINTEROF";
    case NODE_ARRAYOF: return "NODE_ARRAYOF";
    case NODE_ARRAYFILL: return "NODE_ARRAYFILL";
    case NODE_ARGLIST: return "NODE_ARGLIST";
    case NODE_ARGPAIR: return "NODE_ARGPAIR";
    case NODE_KEYVALUE_PAIR: return "NODE_KEYVALUE_PAIR";
    case NODE_TYPEKW: return "NODE_TYPEKW";
    case NODE_CLASSMEMBER: return "NODE_CLASSMEMBER";
    case NODE_CLASSFILL: return "NODE_CLASSFILL";
    default: return "UNKNOWN_astnode_type_t";
  }
}

// Auto-generated function for intercode_type_t
const char* codetype_tostr(intercode_type_t type) {
  switch(type) {
    case CODE_DEF_FUNC: return "CODE_DEF_FUNC";
    case CODE_DEF_FUNC_END: return "CODE_DEF_FUNC_END";
    case CODE_SCOPE_END: return "CODE_SCOPE_END";
    case CODE_DECLARE: return "CODE_DECLARE";
    case CODE_EXTERN_DECLARE: return "CODE_EXTERN_DECLARE";
    case CODE_ALLOC_GLOBAL: return "CODE_ALLOC_GLOBAL";
    case CODE_ALLOC_LOCAL: return "CODE_ALLOC_LOCAL";
    case CODE_ALLOC_TMP: return "CODE_ALLOC_TMP";
    case CODE_FREE: return "CODE_FREE";
    case CODE_RETURN: return "CODE_RETURN";
    case CODE_MOV: return "CODE_MOV";
    case CODE_ADD: return "CODE_ADD";
    case CODE_SUB: return "CODE_SUB";
    case CODE_MUL: return "CODE_MUL";
    case CODE_DIV: return "CODE_DIV";
    case CODE_MOD: return "CODE_MOD";
    case CODE_REFER: return "CODE_REFER";
    case CODE_DEFER: return "CODE_DEFER";
    case CODE_BITAND: return "CODE_BITAND";
    case CODE_BITOR: return "CODE_BITOR";
    case CODE_BITNOT: return "CODE_BITNOT";
    case CODE_CMP: return "CODE_CMP";
    case CODE_JMP: return "CODE_JMP";
    case CODE_JA: return "CODE_JA";
    case CODE_JAE: return "CODE_JAE";
    case CODE_JB: return "CODE_JB";
    case CODE_JBE: return "CODE_JBE";
    case CODE_JE: return "CODE_JE";
    case CODE_JNE: return "CODE_JNE";
    case CODE_LABEL: return "CODE_LABEL";
    case CODE_PUSHARG: return "CODE_PUSHARG";
    case CODE_FUNCCALL: return "CODE_FUNCCALL";
    case CODE_STORE_RETV: return "CODE_STORE_RETV";
    case CODE_DATA: return "CODE_DATA";
    case CODE_LOAD: return "CODE_LOAD";
    case CODE_STORE: return "CODE_STORE";
    case CODE_M2M: return "CODE_M2M";
    case CODE_GLOBAL_VAR_DATA: return "CODE_GLOBAL_VAR_DATA";
    case CODE_DATA_SECTION: return "CODE_DATA_SECTION";
    case CODE_TEXT_SECTION: return "CODE_TEXT_SECTION";
    default: return "UNKNOWN_intercode_type_t";
  }
}
